### ISSUE TITLE
 v1.1.0 has not been released yet?

### ISSUE THREAD

**Issue by shiyiya** [kushalmahapatro/cuberto_bottom_bar#8]
https://github.com/kushalmahapatro/cuberto_bottom_bar/blob/9f9231d9c0665fbb8ed291ea9305862416524e23/lib/cuberto_bottom_bar.dart#L190

I see #6 can change barshadow,  but it's still version 1.0.0 on [pub.dev](https://pub.dev/packages/cuberto_bottom_bar) ?

**Comment by Zazo032** [comment]
@kushalmahapatro has yet to push the new version to pub.dev

As a temporary workaround, you can import that version like this:
```yaml
cuberto_bottom_bar:
    git:
      url: https://github.com/Zazo032/cuberto_bottom_bar.git
```

**Comment by kushalmahapatro** [comment]
@shiyiya  I am going to publish  1.1.0 by today's EOD, till then u can use 
```yaml
cuberto_bottom_bar:
    git:
      url: https://github.com/Zazo032/cuberto_bottom_bar.git
```
as mentioned by @Zazo032
